module.exports = {
  appUpdateInterval: process.env.APP_UPDATE_INTERVAL || (20*60*1000),
  sdeConnectionString: process.env.DB_CONNECTION_STRING || require('./sdeCredentials'),
  storageConnectionString: process.env.STORAGE_CONNECTION_STRING || require('./storageCredentials'),
  crestEndPoint: process.env.CREST_END_POINT || 'https://crest-tq.eveonline.com/',
  crestCacheDuration: process.env.CREST_CACHE_DURATION || (20*60*1000),
  primalistURL: process.env.PRIMALIST_URL || 'http://primalist.herokuapp.com/api/',
  priceTresholdMultiplier: process.env.PRICE_THRESHOLD_MULTIPLIER || 1.25,
  priceRecommandedMultiplier: process.env.PRICE_THRESHOLD_RECOMMANDED_MULTIPLIER || 1.20,
  maxSmallItemSize: process.env.MAX_ITEM_SIZE || 200,
  minBigItemSize: process.env.MIN_BIG_ITEM_SIZE || 1000,
  limiter: process.env.LIMITER || 2000,
  crestDelay: process.env.CREST_DELAY || 200,
  eveCentralApiUrl: process.env.EVECENTRAL_API_URL || 'http://api.eve-central.com/api/marketstat/json',
  eveCentralCacheDuration: process.env.EVECENTRAL_CACHE_DURATION || (60*60*1000),
  eveCentralChunk: process.env.EVECENTRAL_CHUNK || 200,
  eveCentralDelay: process.env.EVECENTRAL_DELAY || 400,
  filteredItemList: (process.env.FILTEREDITEMLIST || '36913').split(','),
  appUrl: process.env.APP_URL || 'http://localhost:8080',
  useExternalStorage: process.env.SAVE_DATA || false,
  referenceSystemHub: process.env.APP_REFERENCE_SYSTEM_HUB || 'Jita',
  targetSystem: process.env.APP_TARGET_SYSTEM || 'DO6H-Q'
};